import { mkdir } from "fs/promises";
import path from "path";

// Uploaded media lives in a data dir OUTSIDE /public (Next doesn't serve
// runtime-written public files in production) and is streamed back through an
// auth-gated route handler. The dir is a mounted volume in Docker (see DEPLOY.md)
// and is backed up alongside the DB.
export const UPLOADS_DIR = path.join(process.cwd(), "uploads");

// ── Part photos (one per part) ───────────────────────────────────────────────
export function partsPhotoDir(): string {
  return path.join(UPLOADS_DIR, "parts");
}

export function partPhotoFile(partId: number): string {
  return path.join(partsPhotoDir(), `part-${partId}.jpg`);
}

export async function ensurePartsPhotoDir(): Promise<void> {
  await mkdir(partsPhotoDir(), { recursive: true });
}

// ── Job photos (many per work order; filename is a stored uuid) ───────────────
export function jobPhotoDir(): string {
  return path.join(UPLOADS_DIR, "jobs");
}

// The stored path is generated by us (uuid.jpg); basename() is belt-and-braces
// against any traversal in a value that reaches here from the DB.
export function jobPhotoFile(filename: string): string {
  return path.join(jobPhotoDir(), path.basename(filename));
}

export async function ensureJobPhotoDir(): Promise<void> {
  await mkdir(jobPhotoDir(), { recursive: true });
}

// Trust the bytes, not the client-declared MIME: check real image magic numbers.
// Shared by every upload route so one definition governs what counts as an image.
export function looksLikeImage(b: Buffer): boolean {
  if (b.length < 12) return false;
  if (b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff) return true; // JPEG
  if (b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47)
    return true; // PNG
  if (b[0] === 0x47 && b[1] === 0x49 && b[2] === 0x46) return true; // GIF
  if (
    b[0] === 0x52 &&
    b[1] === 0x49 &&
    b[2] === 0x46 &&
    b[3] === 0x46 &&
    b[8] === 0x57 &&
    b[9] === 0x45 &&
    b[10] === 0x42 &&
    b[11] === 0x50
  )
    return true; // WEBP (RIFF....WEBP)
  return false;
}
